{% set name = "radical.analytics" %}
{% set version = "0.90.7" %}
{% set sha256 = "91a11e920f55381f8989b9d714ae99094eb248e70443957f0cc6e03eb55d461c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [py3k or win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - radical.utils
    - matplotlib
    - psutil
    - pandas
    - numpy
    - sqlalchemy
    - radical.pilot
    - more-itertools
    
test:
  imports:
    - radical.analytics
  
about:
  home: https://github.com/radical-cybertools/radical.analytics
  license: GPL2
  license_family: GPL2
  license_file: LICENSE
  summary: 'RADICAL-Anlytics is a library supporting the analysis of data produced by 
    RADICAL-Cybertools.'
  description: |
    RADICAL-Anlytics is a library supporting the analysis of data produced by 
    RADICAL-Cybertools. Currently, RADICAL-Analytics supports RADICAL-Pilot and
    RADICAL-EnTK, and it has been used to support and develop the experimental 
    analysis published by the RADICAL Group at Rutgers University.
  dev_url: https://github.com/radical-cybertools/radical.analytics
  doc_url: https://radicalanalytics.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andre-merzky
    - iparask
