{% set name = "radical.analytics" %}
{% set version = "1.47.0" %}
{% set sha256 = "35329aedc6746d3c5f77f9f6ce78c9a05dd4c88da127a6a70613acb1d4702ec1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py2k or win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - radical.utils >=1.40
    - matplotlib >=3.1.2
    - psutil
    - pandas
    - numpy
    - sqlalchemy
    - more-itertools

test:
  imports:
    - radical.analytics

about:
  home: https://github.com/radical-cybertools/radical.analytics
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: RADICAL-Anlytics is a library supporting the analysis of data produced by RADICAL-Cybertools.
  description: |
    RADICAL-Anlytics is a library supporting the analysis of data produced by 
    RADICAL-Cybertools. Currently, RADICAL-Analytics supports RADICAL-Pilot and
    RADICAL-EnTK, and it has been used to support and develop the experimental 
    analysis published by the RADICAL Group at Rutgers University.
  dev_url: https://github.com/radical-cybertools/radical.analytics
  doc_url: https://radicalanalytics.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
    - mturilli
