{% set name = "radical.analytics" %}
{% set version = "1.6.7" %}
{% set sha256 = "9634f8070ae0a68c1f5519286a61e54467fe6e9fd1b5aadf69bec7ce72c3fe92" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py2k or win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - radical.utils >=1.4
    - matplotlib >=3.1.2
    - psutil
    - pandas
    - numpy
    - sqlalchemy
    - more-itertools

test:
  imports:
    - radical.analytics

about:
  home: https://github.com/radical-cybertools/radical.analytics
  license: GPL-2.0-only
  license_family: GPL2
  license_file: LICENSE
  summary: RADICAL-Anlytics is a library supporting the analysis of data produced by RADICAL-Cybertools.
  description: |
    RADICAL-Anlytics is a library supporting the analysis of data produced by 
    RADICAL-Cybertools. Currently, RADICAL-Analytics supports RADICAL-Pilot and
    RADICAL-EnTK, and it has been used to support and develop the experimental 
    analysis published by the RADICAL Group at Rutgers University.
  dev_url: https://github.com/radical-cybertools/radical.analytics
  doc_url: https://radicalanalytics.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andre-merzky
    - iparask
    - mturilli
