appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jY1WemGIA6uc4mV+E0Pj919BCmVIQXrXDpxwesBJTTtxG4uK3pNryt4UEhfFOg0jj3jcq3WIU0RSeLIz4iob6yQEJDLpCHC+oT1+MvHxQplJv6r44s9eIRMPPA9JH0dvizOQBDdt6fRMVfpB/XxkfKlazAG6aC+1p2XFzlVarQzA0URAUamVclDbnDeEw7A809aWp/Fi1xp5x64TLQTTs4wB3C7pxNuP0dYLKzO4omle6zy6Vmwy26d3AveER1WotRD2EvK5yY9F9M+H0MO7M3eRFwXOg2KAOA9jcNUtJw7/cNi2STkdQZyIQnzh7ASrvNLiJnhjRvt+dN3xmDIszUWwbHFslOh/1q0DQeock8CHrKRTJALW9yA+zQn4OG0iaJD7F2Tf5MrTUj6E3Vyi3LbESyf7xQiVyxKoArhFUv2lXnSLSqHpNicL2MUw/NysRHFLll4hN9uTtzhbxs5nDywO/ctVTDI3Szb5qP3t9uIZGsJUJ4R1PMUA3p3zbRNqht2xHEsFnENA+IU1/6pet7jaUUuYqMances/ZyPbUjyzLQPy6+Tr81wPvEspsnYLV/FSNWi4wWPOvfWzBEmvlWM867TQywfM5IvjOygBm2o8D2OQu3UJQ0krI8TSE5EhgOb+BwaW9/2iBskJr/17kA6nH1wLJvqciAyVZI6AiQA=}
