travis:
  secure:
    BINSTAR_TOKEN: NwzOpyQW/AkkS+dTYQg2IYE3L3ndTjIK3EWvnbB0XQMXLBI292kQptH6o7x3SHJxTWiQVGJM1hFEkqxSozSlcG/Q19ZO1+TERYsJnNJPAKH/w6GffPnoCTmRlvmpeId7A/yBrR/8wQDN/t4Ka/Rtf+HvSU7XeKOT2ja25o/NIOPRnCTyqesv6mllwyt7TLKhuhTcOqfl53rbCqfb+jL4uWZIURQvnC7K/TSFdl9VLDDiOBkv0EfCc2K4c7ImwDPp3KxZp6CX3E1ST77QvHWbr+95VXjJCGC/YjjMTuV8khkB4nhXibwoalV6EkQBJjRj9L82OohGKyAlo6KoDzkOtsUzFioNv4c9b/TuMTNQFq1f7KXnbfsxyJvZ0z0Kh8jL4MjawxbeD2FHwfTSUtTY131HVbzVAX7zWJhsEYLBDOnfyUQM4d/E3jAMeOrnhh2FLi3Ny7cwqzeZKOteEsiHhhO9MsPQBMjTOnLeuDmCNmzeiqui8wPEKGMmeSgamp+4L+fB1jPRuebeLE2l6x7OVg5cb1z6uN3DBr+bRRGf1vN5GQ3D86OgCrudVpzH6+3muK/nnThOfefhkLcs5coAW4KKCf5Vx9z4s28ztdXs7UfphqAfcwdWfw8XdKmCKOPCT2gEmvUO34oITzD1STBZgzb39X4ET+TcJ1JVQIXJK5Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
